############################################
# HUSKY GAMING Teclado Gamer Husky Blizzard
# Magic Fn Layer (Caps = Modifier)
############################################

device_name = "HUSKY GAMING Teclado Gamer Husky Blizzard"

# Prevent CapsLock from toggling caps.
# When tapped alone, it does nothing.
# When held, it acts as a modifier layer.
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_CAPSLOCK"]
tap = []

################################
# IJKL - Arrow Keys (while holding Caps)
################################

[[remap]]
input = ["KEY_CAPSLOCK", "KEY_I"]
output = ["KEY_UP"]

[[remap]]
input = ["KEY_CAPSLOCK", "KEY_K"]
output = ["KEY_DOWN"]

[[remap]]
input = ["KEY_CAPSLOCK", "KEY_J"]
output = ["KEY_LEFT"]

[[remap]]
input = ["KEY_CAPSLOCK", "KEY_L"]
output = ["KEY_RIGHT"]



#####################################################
# ESC behavior (PT-BR FIX)
#################################################

# CAPS + ESC = ESC real
[[remap]]
input = ["KEY_CAPSLOCK", "KEY_ESC"]
output = ["KEY_ESC"]

# SHIFT + ESC = "
[[remap]]
input = ["KEY_LEFTSHIFT", "KEY_ESC"]
output = ["KEY_LEFTSHIFT", "KEY_GRAVE"]

[[remap]]
input = ["KEY_RIGHTSHIFT", "KEY_ESC"]
output = ["KEY_LEFTSHIFT", "KEY_GRAVE"]

# ESC sozinho = '
[[remap]]
input = ["KEY_ESC"]
output = ["KEY_GRAVE"]

################################
# Backspace - Delete (while holding Caps)
################################

[[remap]]
input = ["KEY_CAPSLOCK", "KEY_BACKSPACE"]
output = ["KEY_DELETE"]


[[remap]]
input = ["KEY_CAPSLOCK", "KEY_LEFTBRACE"]
output = ["KEY_HOMEPAGE"]

[[remap]]
input = ["KEY_CAPSLOCK", "KEY_RIGHTBRACE"]
output = ["KEY_HOME"]

